# https://github.com/peripheryapp/periphery/blob/master/.github/workflows/test.yml

name: Test
on:
  push:
    branches:
      - main
  pull_request: {}
env:
  swift_package_resolve: swift package resolve
  swift_build: swift build --build-tests
  swift_test: swift test
  cache_version: 1
jobs:
  test:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["6.1", "6.2"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: swift-actions/setup-swift@v3
        with:
          swift-version: ${{ matrix.swift }}
          skip-verify-signature: true
      - name: Cache resolved dependencies
        id: cache-resolved-dependencies
        uses: actions/cache@v4
        with:
          path: |
            .build
            Package.resolved
          key: ${{ matrix.cache-version }}-${{ runner.os }}-${{ matrix.swift }}-${{ env.cache_version }}-spm-deps-${{ hashFiles('Package.swift', 'Package.resolved') }}
          restore-keys: |
            ${{ matrix.cache-version }}-${{ runner.os }}-${{ matrix.swift }}-${{ env.cache_version }}-spm-deps-
      - name: Resolve dependencies
        if: steps.cache-resolved-dependencies.outputs.cache-hit != 'true'
        run: ${{ env.swift_package_resolve }}
      - name: Build
        run: ${{ env.swift_build }}
      - name: Test
        run: ${{ env.swift_test }}
